export const languageData = [
  {
    locale: 'en',
    translation: {
      home: 'Home',
      favorites: 'Favorites',
      offer: 'Offer',
      messages: 'Messages',
      profile: 'Profile',
      create_your_account: 'Create your account',
      first_name: 'First Name',
      last_name: 'Last Name',
      email: 'Email',
      your_email: 'Your email',
      password: 'Password',
      register: 'Register',
      already_have_an_account: 'Do you already have an account?',
      dont_have_an_account: `Don't have an account?`,
      login: 'Login',
      successful_registration: 'Successful registration!',
      register_success_msg:
        'Your account has been created successfully. Now you can explore and enjoy all the features our app has to offer.',
      back_to_top: 'Back to top',
      something_went_wrong: 'Something went wrong!',
      forget_password_msg: `Forgot your password? Don't worry, we'll help you reset it. Enter the email address associated with your account and we'll send you a link to create a new password.`,
      register_fail_msg:
        'It seems there was a problem processing your registration. Please try again or contact support if the problem persists.',
      forget_password: 'I have forgotten my password',
      sign_up: 'Sign up',
      recover_password: 'Recover password',
      login_fail_msg:
        'It seems there was a problem logging in. Please try again or contact support if the problem persists.',
      repeat_email: 'Repeat your email',
      send_reset_link: 'Send reset link',
      mail_sent: 'Mail sent!',
      link_sent_msg:
        'We have sent a password reset link to your email. Please check your inbox and follow the instructions to create a new password.',
      reset_password: 'Reset password',
      new_password: 'New password',
      repeat_password: 'Repeat the new password',
      save_password: 'Save password',
      password_reset: 'Password reset!',
      password_save_msg:
        'Your new password has been saved successfully. You can now use your new password to log in to your account.',
      password_save_fail_msg:
        'It seems there was a problem saving your password. Please try again or contact support if the problem persists.',
      first_name_required: 'First name is required',
      last_name_required: 'Last name is required',
      invalid_email: 'Invalid email address',
      password_min_length: 'Password must be at least 6 characters',
      email_required: 'Email is required',
      password_required: 'Password is required',
      passwords_must_match: 'Passwords must match',
      confirm_password_required: 'Confirm password is required',
    },
  },
  {
    locale: 'sp',
    translation: {
      home: 'Hogar',
      favorites: 'Favoritos',
      offer: 'Ofrecer',
      messages: 'Mensajes',
      profile: 'Perfil',
      create_your_account: 'Crea tu cuenta',
      first_name: 'Nombre de pila',
      last_name: 'Apellido',
      email: 'Email',
      your_email: 'Tu email',
      password: 'Contraseña',
      register: 'Registrarme',
      already_have_an_account: '¿Ya tienes una cuenta?',
      dont_have_an_account: '¿No tienes una cuenta?',
      login: 'Iniciar sesión',
      successful_registration: '¡Registro exitoso!',
      register_success_msg:
        'Tu cuenta ha sido creada exitosamente. Ahora podrás explorar y disfrutar de todas las funcionalidades que nuestra app tiene para ofrecer.',
      back_to_top: 'Volver al inicio',
      something_went_wrong: '¡Algo salió mal!',
      forget_password_msg:
        '¿Has olvidado tu contraseña? No te preocupes, te ayudaremos a restablecerla. Ingresa tu correo electrónico asociado a tu cuenta y te enviaremos un enlace para crear una nueva contraseña.',
      register_fail_msg:
        'Parece que hubo un problema al procesar tu registro. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      forget_password: 'He olvidado mi contraseña',
      sign_up: 'Regístrate',
      recover_password: 'Recuperar la contraseña',
      login_fail_msg:
        'Parece que hubo un problema al iniciar la sesión. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      repeat_email: 'Repite tu email',
      send_reset_link: 'Enviar enlace de restablecimiento',
      mail_sent: '¡Correo enviado!',
      link_sent_msg:
        'Hemos enviado un enlace de restablecimiento de contraseña a tu correo electrónico. Por favor, revisa tu bandeja de entrada y sigue las instrucciones para crear una nueva contraseña.',
      reset_password: 'Restablecer la contraseña',
      new_password: 'Nueva contraseña',
      repeat_password: 'Repite la nueva contraseña',
      save_password: 'Guardar la contraseña',
      password_reset: '¡Contraseña restablecida!',
      password_save_msg:
        'Tu nueva contraseña ha sido guardada con éxito. Ya puedes usar tu nueva contraseña para iniciar sesión en tu cuenta.',
      password_save_fail_msg:
        'Parece que hubo un problema al guardar tu contraseña. Por favor, intenta nuevamente o contacta con soporte si el problema persiste.',
      first_name_required: 'El nombre es obligatorio',
      last_name_required: 'El apellido es obligatorio',
      invalid_email: 'Dirección de correo electrónico no válida',
      password_min_length: 'La contraseña debe tener al menos 6 caracteres',
      email_required: 'El correo electrónico es obligatorio',
      password_required: 'La contraseña es obligatoria',
      passwords_must_match: 'Las contraseñas deben coincidir',
      confirm_password_required: 'Se requiere confirmar la contraseña',
    },
  },
];

export const appLanguages = [
  {
    id: '0',
    name: 'English',
    code: 'en',
  },
  {
    id: '1',
    name: 'spanish',
    code: 'sp',
  },
];
